//go:build e2e

package app

import (
	"encoding/json"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/shini4i/argo-compare/internal/appset"
	"github.com/shini4i/argo-compare/internal/models"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// generatedApp is the projection both sides are compared on. ArgoCD adds
// ownership, finalizers and status that argo-compare never produces, so only the
// fields expansion itself decides appear here.
type generatedApp struct {
	Name           string
	RepoURL        string
	Path           string
	Chart          string
	TargetRevision string
	ReleaseName    string
	Values         string
	Sources        []generatedSource
}

// generatedSource is one entry of a multi-source Application's spec.sources,
// including the ref name and valueFiles that a "$ref" layout depends on.
type generatedSource struct {
	RepoURL        string
	Path           string
	Chart          string
	TargetRevision string
	Ref            string
	ReleaseName    string
	ValueFiles     []string
	Values         string
}

// clusterSource is one source as the cluster reports it, shared by spec.source
// and spec.sources.
type clusterSource struct {
	RepoURL        string `json:"repoURL"`
	Path           string `json:"path"`
	Chart          string `json:"chart"`
	TargetRevision string `json:"targetRevision"`
	Ref            string `json:"ref"`
	Helm           struct {
		ReleaseName string   `json:"releaseName"`
		Values      string   `json:"values"`
		ValueFiles  []string `json:"valueFiles"`
	} `json:"helm"`
}

// TestE2EApplicationSetParity compares argo-compare's expansion against the
// Applications the real ArgoCD ApplicationSet controller generated from the same
// manifest at the same commit. It lives in this package on purpose: it drives
// the production gitTree adapter rather than a reimplementation of it.
func TestE2EApplicationSetParity(t *testing.T) {
	repoDir := requireEnv(t, "E2E_REPO_DIR")
	fixturesDir := requireEnv(t, "E2E_FIXTURES_DIR")
	originURL := requireEnv(t, "E2E_ORIGIN_URL")
	branch := envOr("E2E_BRANCH", "main")

	tree := branchTree(t, repoDir, branch)

	for _, name := range []string{"e2e-list", "e2e-git-dir", "e2e-git-file", "e2e-lifecycle", "e2e-funcs", "e2e-git-values", "e2e-ref"} {
		t.Run(name, func(t *testing.T) {
			manifest := filepath.Join(fixturesDir, strings.Replace(name, "e2e-", "appset-", 1)+".yaml")
			raw, err := os.ReadFile(manifest) // #nosec G304 -- a lab fixture path
			require.NoError(t, err)

			appSet, err := parseApplicationSetContent([]byte(strings.ReplaceAll(string(raw), "REPO_URL", originURL)))
			require.NoError(t, err, "argo-compare rejected a manifest the real controller accepted")

			apps, err := appset.Expand(appSet, gitTree{tree: tree})
			require.NoError(t, err)

			assert.Equal(t, argoGenerated(t, name), normalizeGenerated(t, apps),
				"argo-compare's expansion must match what the ArgoCD controller generated")
		})
	}
}

// argoGenerated reads what the real controller produced for one ApplicationSet.
func argoGenerated(t *testing.T, appSetName string) []generatedApp {
	t.Helper()

	ctx := envOr("KCTX", "kind-ac-e2e")
	// The controller links what it generated by ownerReference, not by a label,
	// so every Application is fetched and filtered on the owner below.
	out, err := exec.Command("kubectl", "--context", ctx, "-n", "argocd", // #nosec G204 -- lab-controlled args
		"get", "applications", "-o", "json").Output()
	require.NoError(t, err, "reading generated Applications from the cluster")

	var list struct {
		Items []struct {
			Metadata struct {
				Name            string `json:"name"`
				OwnerReferences []struct {
					Kind string `json:"kind"`
					Name string `json:"name"`
				} `json:"ownerReferences"`
			} `json:"metadata"`
			Spec struct {
				Source  clusterSource   `json:"source"`
				Sources []clusterSource `json:"sources"`
			} `json:"spec"`
		} `json:"items"`
	}
	require.NoError(t, json.Unmarshal(out, &list))

	got := make([]generatedApp, 0, len(list.Items))
	for _, item := range list.Items {
		if !ownedBy(item.Metadata.OwnerReferences, appSetName) {
			continue
		}
		src := item.Spec.Source
		got = append(got, generatedApp{
			Name:           item.Metadata.Name,
			RepoURL:        src.RepoURL,
			Path:           src.Path,
			Chart:          src.Chart,
			TargetRevision: src.TargetRevision,
			ReleaseName:    src.Helm.ReleaseName,
			Values:         canonicalYAML(t, src.Helm.Values),
			Sources:        clusterSources(t, item.Spec.Sources),
		})
	}
	require.NotEmpty(t, got, "the controller generated nothing for %s", appSetName)
	sortGenerated(got)

	return got
}

// ownedBy reports whether an Application was generated by <appSetName>.
func ownedBy(refs []struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}, appSetName string) bool {
	for _, ref := range refs {
		if ref.Kind == "ApplicationSet" && ref.Name == appSetName {
			return true
		}
	}

	return false
}

// normalizeGenerated projects argo-compare's expansion onto the same shape.
func normalizeGenerated(t *testing.T, apps []models.Application) []generatedApp {
	t.Helper()

	got := make([]generatedApp, 0, len(apps))
	for i := range apps {
		app := generatedApp{Name: apps[i].Metadata.Name, Sources: expandedSources(t, apps[i].Spec.Sources)}
		if src := apps[i].Spec.Source; src != nil {
			app.RepoURL = src.RepoURL
			app.Path = src.Path
			app.Chart = src.Chart
			app.TargetRevision = src.TargetRevision
			app.ReleaseName = src.Helm.ReleaseName
			app.Values = canonicalYAML(t, src.Helm.Values)
		} else {
			require.NotEmpty(t, app.Sources, "a generated Application has neither source nor sources")
		}
		got = append(got, app)
	}
	sortGenerated(got)

	return got
}

// clusterSources projects the controller's spec.sources onto the shape both
// sides are compared on.
func clusterSources(t *testing.T, sources []clusterSource) []generatedSource {
	t.Helper()

	if len(sources) == 0 {
		return nil
	}
	got := make([]generatedSource, 0, len(sources))
	for _, src := range sources {
		got = append(got, generatedSource{
			RepoURL:        src.RepoURL,
			Path:           src.Path,
			Chart:          src.Chart,
			TargetRevision: src.TargetRevision,
			Ref:            src.Ref,
			ReleaseName:    src.Helm.ReleaseName,
			ValueFiles:     src.Helm.ValueFiles,
			Values:         canonicalYAML(t, src.Helm.Values),
		})
	}

	return got
}

// expandedSources is clusterSources for argo-compare's own expansion. Source
// order is spec order on both sides, so it is compared as written.
func expandedSources(t *testing.T, sources []*models.Source) []generatedSource {
	t.Helper()

	if len(sources) == 0 {
		return nil
	}
	got := make([]generatedSource, 0, len(sources))
	for _, src := range sources {
		require.NotNil(t, src, "a generated Application has a nil source entry")
		got = append(got, generatedSource{
			RepoURL:        src.RepoURL,
			Path:           src.Path,
			Chart:          src.Chart,
			TargetRevision: src.TargetRevision,
			Ref:            src.Ref,
			ReleaseName:    src.Helm.ReleaseName,
			ValueFiles:     src.Helm.ValueFiles,
			Values:         canonicalYAML(t, src.Helm.Values),
		})
	}

	return got
}

// canonicalYAML re-marshals a values block so the comparison is about content
// rather than the indentation each side's templating happened to emit. It fails
// the test if the block is not exactly one YAML document.
func canonicalYAML(t *testing.T, values string) string {
	t.Helper()

	if strings.TrimSpace(values) == "" {
		return ""
	}

	// A decoder rather than Unmarshal: a values block whose indentation breaks
	// mid-way parses as two documents, and Unmarshal returns the first without
	// complaint, so half the block would silently drop out of the comparison.
	decoder := yaml.NewDecoder(strings.NewReader(values))

	var parsed any
	require.NoError(t, decoder.Decode(&parsed), "values is not YAML: %q", values)
	require.ErrorIs(t, decoder.Decode(new(any)), io.EOF, "values is more than one YAML document: %q", values)

	out, err := yaml.Marshal(parsed)
	require.NoError(t, err)

	return string(out)
}

func sortGenerated(apps []generatedApp) {
	sort.Slice(apps, func(i, j int) bool { return apps[i].Name < apps[j].Name })
}

// branchTree resolves one branch of the local clone to the tree expansion reads.
func branchTree(t *testing.T, repoDir, branch string) *object.Tree {
	t.Helper()

	repo, err := git.PlainOpen(repoDir)
	require.NoError(t, err)

	hash, err := repo.ResolveRevision(plumbing.Revision("refs/remotes/origin/" + branch))
	require.NoError(t, err, "resolving origin/%s in %s", branch, repoDir)

	commit, err := repo.CommitObject(*hash)
	require.NoError(t, err)

	tree, err := commit.Tree()
	require.NoError(t, err)

	return tree
}

func requireEnv(t *testing.T, key string) string {
	t.Helper()

	value := os.Getenv(key)
	require.NotEmpty(t, value, "%s is required (set by the e2e Taskfile)", key)

	return value
}

func envOr(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}

	return fallback
}
