//go:build e2e

package app

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/shini4i/argo-compare/internal/appset"
	"github.com/shini4i/argo-compare/internal/models"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

// generatedApp is the projection both sides are compared on. ArgoCD adds
// ownership, finalizers and status that argo-compare never produces, so only the
// fields expansion itself decides appear here.
type generatedApp struct {
	Name           string
	RepoURL        string
	Path           string
	Chart          string
	TargetRevision string
	ReleaseName    string
	Values         string
}

// TestE2EApplicationSetParity compares argo-compare's expansion against the
// Applications the real ArgoCD ApplicationSet controller generated from the same
// manifest at the same commit. It lives in this package on purpose: it drives
// the production gitTree adapter rather than a reimplementation of it.
func TestE2EApplicationSetParity(t *testing.T) {
	repoDir := requireEnv(t, "E2E_REPO_DIR")
	fixturesDir := requireEnv(t, "E2E_FIXTURES_DIR")
	originURL := requireEnv(t, "E2E_ORIGIN_URL")
	branch := envOr("E2E_BRANCH", "main")

	tree := branchTree(t, repoDir, branch)

	for _, name := range []string{"e2e-list", "e2e-git-dir", "e2e-git-file", "e2e-lifecycle"} {
		t.Run(name, func(t *testing.T) {
			manifest := filepath.Join(fixturesDir, strings.Replace(name, "e2e-", "appset-", 1)+".yaml")
			raw, err := os.ReadFile(manifest) // #nosec G304 -- a lab fixture path
			require.NoError(t, err)

			appSet, err := parseApplicationSetContent([]byte(strings.ReplaceAll(string(raw), "REPO_URL", originURL)))
			require.NoError(t, err, "argo-compare rejected a manifest the real controller accepted")

			apps, err := appset.Expand(appSet, gitTree{tree: tree})
			require.NoError(t, err)

			assert.Equal(t, argoGenerated(t, name), normalizeGenerated(t, apps),
				"argo-compare's expansion must match what the ArgoCD controller generated")
		})
	}
}

// argoGenerated reads what the real controller produced for one ApplicationSet.
func argoGenerated(t *testing.T, appSetName string) []generatedApp {
	t.Helper()

	ctx := envOr("KCTX", "kind-ac-e2e")
	// The controller links what it generated by ownerReference, not by a label,
	// so every Application is fetched and filtered on the owner below.
	out, err := exec.Command("kubectl", "--context", ctx, "-n", "argocd", // #nosec G204 -- lab-controlled args
		"get", "applications", "-o", "json").Output()
	require.NoError(t, err, "reading generated Applications from the cluster")

	var list struct {
		Items []struct {
			Metadata struct {
				Name            string `json:"name"`
				OwnerReferences []struct {
					Kind string `json:"kind"`
					Name string `json:"name"`
				} `json:"ownerReferences"`
			} `json:"metadata"`
			Spec struct {
				Source struct {
					RepoURL        string `json:"repoURL"`
					Path           string `json:"path"`
					Chart          string `json:"chart"`
					TargetRevision string `json:"targetRevision"`
					Helm           struct {
						ReleaseName string `json:"releaseName"`
						Values      string `json:"values"`
					} `json:"helm"`
				} `json:"source"`
			} `json:"spec"`
		} `json:"items"`
	}
	require.NoError(t, json.Unmarshal(out, &list))

	got := make([]generatedApp, 0, len(list.Items))
	for _, item := range list.Items {
		if !ownedBy(item.Metadata.OwnerReferences, appSetName) {
			continue
		}
		src := item.Spec.Source
		got = append(got, generatedApp{
			Name:           item.Metadata.Name,
			RepoURL:        src.RepoURL,
			Path:           src.Path,
			Chart:          src.Chart,
			TargetRevision: src.TargetRevision,
			ReleaseName:    src.Helm.ReleaseName,
			Values:         canonicalYAML(t, src.Helm.Values),
		})
	}
	require.NotEmpty(t, got, "the controller generated nothing for %s", appSetName)
	sortGenerated(got)

	return got
}

// ownedBy reports whether an Application was generated by <appSetName>.
func ownedBy(refs []struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
}, appSetName string) bool {
	for _, ref := range refs {
		if ref.Kind == "ApplicationSet" && ref.Name == appSetName {
			return true
		}
	}

	return false
}

// normalizeGenerated projects argo-compare's expansion onto the same shape.
func normalizeGenerated(t *testing.T, apps []models.Application) []generatedApp {
	t.Helper()

	got := make([]generatedApp, 0, len(apps))
	for i := range apps {
		src := apps[i].Spec.Source
		require.NotNil(t, src, "a generated Application has no source")
		got = append(got, generatedApp{
			Name:           apps[i].Metadata.Name,
			RepoURL:        src.RepoURL,
			Path:           src.Path,
			Chart:          src.Chart,
			TargetRevision: src.TargetRevision,
			ReleaseName:    src.Helm.ReleaseName,
			Values:         canonicalYAML(t, src.Helm.Values),
		})
	}
	sortGenerated(got)

	return got
}

// canonicalYAML re-marshals a values block so the comparison is about content
// rather than the indentation each side's templating happened to emit.
func canonicalYAML(t *testing.T, values string) string {
	t.Helper()

	if strings.TrimSpace(values) == "" {
		return ""
	}

	var parsed any
	require.NoError(t, yaml.Unmarshal([]byte(values), &parsed), "values is not YAML: %q", values)
	out, err := yaml.Marshal(parsed)
	require.NoError(t, err)

	return string(out)
}

func sortGenerated(apps []generatedApp) {
	sort.Slice(apps, func(i, j int) bool { return apps[i].Name < apps[j].Name })
}

// branchTree resolves one branch of the local clone to the tree expansion reads.
func branchTree(t *testing.T, repoDir, branch string) *object.Tree {
	t.Helper()

	repo, err := git.PlainOpen(repoDir)
	require.NoError(t, err)

	hash, err := repo.ResolveRevision(plumbing.Revision("refs/remotes/origin/" + branch))
	require.NoError(t, err, "resolving origin/%s in %s", branch, repoDir)

	commit, err := repo.CommitObject(*hash)
	require.NoError(t, err)

	tree, err := commit.Tree()
	require.NoError(t, err)

	return tree
}

func requireEnv(t *testing.T, key string) string {
	t.Helper()

	value := os.Getenv(key)
	require.NotEmpty(t, value, "%s is required (set by the e2e Taskfile)", key)

	return value
}

func envOr(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}

	return fallback
}
