#!/usr/bin/env bash
# Generated Applications that exist on only ONE branch, and the flags that gate
# them. The other phases all compare Applications present on both sides, so the
# added/removed classification and its --print-*-manifests gating run here for
# the first time against a real repo.
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib.sh
. "${here}/lib.sh"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

build_compare "$work"
clone_gitops "${work}/gitops"
git -C "${work}/gitops" checkout -q "$FEATURE_BRANCH"

# compare <name> [flag...]: one argo-compare run, its output left at
# <work>/<name>.txt for the assertions below.
compare() {
  local name="$1"
  shift
  local out="${work}/${name}.txt" code=0
  (cd "${work}/gitops" && "$COMPARE_BIN" branch "$TARGET_BRANCH" "$@") >"$out" 2>&1 || code=$?
  echo "--- argo-compare ${name}"
  cat "$out"
  echo "--- end"
  # Without this a crash after the ApplicationSet section still satisfies every
  # assertion below, because they only read lines already printed.
  if [[ "$code" -eq 0 ]]; then
    ok "${name}: exit 0"
  else
    bad "${name}: exit ${code}, expected 0"
  fi
  return
}

MANIFEST='apps/lifecycle-appset.yaml'
SKIP_ADD='Skipping added Application \[life-add\]'
SKIP_DROP='Skipping removed Application \[life-drop\]'
COMPARE_KEEP='===> Comparing generated Application: \[life-keep\]'
COMPARE_ADD='===> Comparing generated Application: \[life-add\]'
COMPARE_DROP='===> Comparing generated Application: \[life-drop\]'

compare default
default="${work}/default.txt"

assert_grep "$default" "===> Processing changed ApplicationSet: \\[${MANIFEST}\\]" \
  "the manifest is reached through the changed-file path"
# Read from that section alone: the count carries no Application name, so run-wide
# it would be satisfied by any other ApplicationSet reporting the same figures.
section_lines "$default" "$MANIFEST" >"${work}/appset.section"
assert_grep "${work}/appset.section" \
  "Generates 2 Application\\(s\\) on this branch and 2 on ${TARGET_BRANCH}; comparing 3" \
  "the two generated sets are paired into three comparisons"

# life-keep is generated by both branches, so it is compared whatever the flags
# say — that is the control the two gated cases are read against.
assert_grep "$default" "$COMPARE_KEEP" "the Application both branches generate is compared"
section_diff "$default" life-keep >"${work}/keep.diff"
assert_grep "${work}/keep.diff" '^-replicas: 7$' "life-keep loses its old replica count"
assert_grep "${work}/keep.diff" '^\+replicas: 9$' "life-keep gains its new replica count"

assert_grep "$default" "$SKIP_ADD" "the added Application is skipped by default"
assert_grep "$default" "$SKIP_DROP" "the removed Application is skipped by default"
assert_no_grep "$default" "$COMPARE_ADD" "the added Application is not rendered by default"
assert_no_grep "$default" "$COMPARE_DROP" "the removed Application is not rendered by default"

compare added --print-added-manifests
added="${work}/added.txt"

assert_grep "$added" "$COMPARE_ADD" "--print-added-manifests renders the added Application"
assert_no_grep "$added" "$SKIP_ADD" "--print-added-manifests drops the skip notice"
section_diff "$added" life-add >"${work}/add.diff"
assert_grep "${work}/add.diff" '^\+name: life-add$' "the added Application renders under its own name"
assert_grep "${work}/add.diff" '^\+replicas: 5$' "the added Application renders its own values"
assert_no_grep "${work}/add.diff" '^-' "the added Application has nothing on the target branch"

assert_grep "$added" "$COMPARE_KEEP" "--print-added-manifests still compares the two-sided Application"

# The flags gate independently: asking for added manifests must not also print
# removed ones, or a single --full-output would be all this phase proves.
assert_grep "$added" "$SKIP_DROP" "--print-added-manifests leaves the removed Application skipped"
assert_no_grep "$added" "$COMPARE_DROP" "--print-added-manifests does not render the removed Application"

compare removed --print-removed-manifests
removed="${work}/removed.txt"

assert_grep "$removed" "$COMPARE_DROP" "--print-removed-manifests renders the removed Application"
assert_no_grep "$removed" "$SKIP_DROP" "--print-removed-manifests drops the skip notice"
section_diff "$removed" life-drop >"${work}/drop.diff"
assert_grep "${work}/drop.diff" '^-name: life-drop$' "the removed Application renders under its own name"
assert_grep "${work}/drop.diff" '^-replicas: 2$' "the removed Application renders its own values"
assert_no_grep "${work}/drop.diff" '^\+' "the removed Application has nothing on the feature branch"

assert_grep "$removed" "$COMPARE_KEEP" "--print-removed-manifests still compares the two-sided Application"
assert_grep "$removed" "$SKIP_ADD" "--print-removed-manifests leaves the added Application skipped"
assert_no_grep "$removed" "$COMPARE_ADD" "--print-removed-manifests does not render the added Application"

phase_end lifecycle
