name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # needed to write releases
  packages: write # needed to write packages

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU # required for multi architecture build - https://goreleaser.com/cookbooks/multi-platform-docker-images/?h=multi#other-things-to-pay-attention-to
        uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is important, otherwise it won't checkout the full tree (i.e. no previous tags)

      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: op://github-actions/github/token

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.20.0
          args: release --rm-dist
