name: Run unit tests
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'

      - name: Install mockgen
        run: go install go.uber.org/mock/mockgen@latest

      - name: Install go-junit-report
        run: github.com/jstemmer/go-junit-report/v2@latest

      - name: Generate junit repot
        run: go test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml

      - name: Run tests
        run: make test-coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
